/*
 * Revision History (Newest first)
 * 
 */

package eulerproblems;

/**
 *
 * @author JSKoenig
 */
public class ID002EvenFibonacciNumbers {
    
    /*
    Problem #2
    Each new term in the Fibonacci sequence is generated by adding the previous 
    two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed 
    four million, find the sum of the even-valued terms.
    */

    public void evenFibonacciNumbers() {
        long maxNum = 4000000;
        long prevNum = 0;
        long nextNum = 1;
        long evenTotal = 0;
        while(nextNum <= maxNum) {
            if(nextNum % 2 == 0){
                evenTotal += nextNum;
            }
            long sum = prevNum + nextNum;
            prevNum = nextNum;
            nextNum = sum;
        }
        System.out.println(evenTotal);
    }
}